In [1]:
import numpy as np

In [ ]:
# Creating numpy array

# Using np.array() // 1D,2D
# Using np.zeros()/ ones() / empty() / random()
# Using np.arange()
# Using np.linspace()
# Using copy()
# Using identity()

In [3]:
# using np.array()
arr1 = np.array([1,2,4,5])
print(arr1)
arr2 = np.array([[1,2,4],[4,5,6]])
print(arr2)

[1 2 4 5]
[[1 2 4]
 [4 5 6]]


In [4]:
# using np.zeros()
zero = np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [5]:
zero_2_3 = np.zeros((2,3))
print(zero_2_3)



[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# using np.ones()
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
fulledArray = np.full((5,5),5)
print(fulledArray)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [12]:
# to create array of sequence of numbers. with np.arange()
arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [13]:
arr2 = np.arange(5)
print(arr2)

[0 1 2 3 4]


In [14]:
arr3 = np.arange(0,11)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
# creating identity Matrix,  with np.eye(shape)
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# identity matrix using np.identity()
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# # Creating diagonal Matrix. with diag()
# Diagonal_matrix = np.diag([5,2,10])
arr6 = np.diag([1,2,3])
arr6

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# using np.linspace()
arr7 = np.linspace(1,10,5)
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
# using np.copy()
arr8 = np.copy(arr7)
arr8

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [41]:
# using np.random
arr9 = np.random.rand(5)
arr9

array([0.52219986, 0.1139132 , 0.25631279, 0.1403023 , 0.53336864])

In [42]:
arr10 = np.random.rand(2,5)
arr10

array([[0.04211113, 0.26260005, 0.20202716, 0.49020177, 0.37120259],
       [0.26308681, 0.63425625, 0.19745078, 0.1567701 , 0.19832168]])