In [ ]:
# .shape
# .ndim
# .size
# .itemsize
# .dtype
# astype()

In [1]:
import numpy as np

In [5]:
# To find the shape of the array.
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# To find total number of elements in the array.
print(arr1.size)

6


In [7]:
# To find the number of dimention in the array.
print(arr1.ndim)

2


In [15]:
arr_3d = np.array([[[1,4,8],[5,6,2]],[[9,7,8],[1,4,2]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)

[[[1 4 8]
  [5 6 2]]

 [[9 7 8]
  [1 4 2]]]
3
(2, 2, 3)


In [26]:
# To check the data type of the array.
arrInt = np.array([[1,2,4],[4,2,9]])
print(arrInt)
print(arrInt.dtype)

[[1 2 4]
 [4 2 9]]
int64


In [22]:
arrFloat = np.array([[1,3,5],[6,4.0,9]])
print(arrFloat)
print(arrFloat.dtype)

[[1. 3. 5.]
 [6. 4. 9.]]
float64


In [24]:
# itemsize -> get size of each item in the array.
arrFloat.itemsize

8

In [27]:
arrInt.itemsize

8

In [28]:
# To change to dtype of the array.
arr2 = np.array(["43",'4',"5"])
print(arr2)
print(arr2.dtype)
int_arr = arr2.astype(int)
print(int_arr)
print(int_arr.dtype)

['43' '4' '5']
<U2
[43  4  5]
int64


In [30]:
arr3 = np.array(["43.5",'4',"5"])
float_arr = arr3.astype(float)
print(float_arr)
print(float_arr.dtype)

[43.5  4.   5. ]
float64


In [31]:
Str_arr = float_arr.astype(str)
print(Str_arr)
print(Str_arr.dtype)
print(Str_arr.itemsize)

['43.5' '4.0' '5.0']
<U32
128


In [37]:
a1 = np.array([5,2,1], dtype= 'int')
print(a1)
print(a1.itemsize)

[5 2 1]
8


In [60]:
a2 = np.array([-128,0,127], dtype= 'int8')
print(a2)
print(a2.itemsize)

[-128    0  127]
1
