In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50,60])
# indexing
print(arr[0])
print(arr[5])
print(arr[3])
print(arr[-1])

10
60
40
60


In [3]:
# slicing
arr1 = np.array([10,20,30,40,50,60])
print(arr1[0:3])
print(arr1[0:4:2])
print(arr1[2:])
print(arr1[:3])
print(arr1[::])
print(arr1[::-1])
print(arr1[-5:-2:])  # arr[(size-5):(size-2):] -> arr[1:4:]

[10 20 30]
[10 30]
[30 40 50 60]
[10 20 30]
[10 20 30 40 50 60]
[60 50 40 30 20 10]
[20 30 40]


In [4]:
# fancy indexing - selecting multiple array.
arr2 = np.array([10,20,30,40,50,60])
print(arr2[[0,2,4]])
print(arr2[[0,-1]])
print(arr[[0]])

[10 30 50]
[10 60]
[10]


In [5]:
# Boolean Masking // flitting data based on condition.
arr3 = np.array([10,20,30,40,50,60])
print(arr3[arr3 > 25])
a = arr3[arr3 <= 40]
print(a)

[30 40 50 60]
[10 20 30 40]


In [4]:
import numpy as np
# 2D array.
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr4[1,2])
print(arr4[-2,-1])
print(arr4[1:3])
print(arr4[0])
print(arr4[0][1])
print(arr4[0,1])
print(arr4[:])
print(arr4[:,2])
print(arr4[0,:])

6
6
[[4 5 6]
 [7 8 9]]
[1 2 3]
2
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
[1 2 3]


In [18]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(arr)
# Integer array indexing 
i = np.array([1, 3, 5])
print(i)
print ("Integer array indexing:", arr[i])

cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])

[ 10  20  30  40  50  60  70  80  90 100]
[1 3 5]
Integer array indexing: [20 40 60]

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


In [20]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print (arr[:2, ::2])
print(arr[:,3])

[[-1.  0.]
 [ 4.  6.]]
[4. 0. 8. 2.]


In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
for i in arr:  # print row by row
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [4]:
for i in np.nditer(arr):  # print item by item
    print(i)

1
2
3
4
5
6
7
8
9
