In [2]:
import numpy as np

In [2]:
# mathemetical Opertions in any 2 array. // + - * / ** % 
arr1 = np.array([3,6,7])
arr2 = np.array([2,5,9])

In [3]:
print(arr1+arr2)

[ 5 11 16]


In [4]:
print(arr1-arr2)

[ 1  1 -2]


In [5]:
print(arr1 * arr2)

[ 6 30 63]


In [7]:
print(arr1 / arr2)

[1.5        1.2        0.77777778]


In [8]:
print(arr1 ** 2)

[ 9 36 49]


In [9]:
print(arr1 % 2)

[1 0 1]


In [10]:
print(arr1 // arr2)

[1 1 0]


In [12]:
# Aggregation functions // min max mean sum std(standard deviation) var(varians)
arr = np.array([10,20,30,40,50,60,70])

In [15]:
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.var(arr))

10
70
40.0
280
20.0
400.0


In [21]:
a = np.array([1,1,2,3,3,3,4,5])
print(np.mean(a))
print(np.median(a))

2.75
3.0


In [2]:
import numpy as np
# To find the absolute value of given array.
a1 = np.array([1,-2,-5,0,-4,9,2])
print(a1)
print(np.absolute(a1))

[ 1 -2 -5  0 -4  9  2]
[1 2 5 0 4 9 2]


In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
print("Array 1:", arr1)
print("Array 2:", arr2)

# Applying a binary operation: add , subtract , multiply, divide, power , mod
add = np.add(arr1,arr2)
sub = np.subtract(arr1,arr2)
div = np.divide(arr1,arr2)
mul = np.multiply(arr1,arr2)
power = np.power(arr1,arr2)
exp = np.exp(arr1)
mod = np.mod(arr1,arr2)
sqrt = np.sqrt(arr2)

print("Addition Result:", add)
print("Subtrtaction Result:", sub)
print("Division Result:", div)
print("Multiplication Result:", mul)
print("Exponentiation Result:", power)
print("Modulus Result:", mod)
print("Exponentent (e to the power) Result:", exp)
print("Square Root Result:", sqrt)

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]
Subtrtaction Result: [-3 -3 -3]
Division Result: [0.25 0.4  0.5 ]
Multiplication Result: [ 4 10 18]
Exponentiation Result: [  1  32 729]
Modulus Result: [1 2 3]
Exponentent (e to the power) Result: [ 2.71828183  7.3890561  20.08553692]
Square Root Result: [2.         2.23606798 2.44948974]


In [32]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[4, 3],[2, 1]])
               
print ("Adding 1 to every element:", a + 10)

print ("\nSubtracting 2 from each element:", b - 10)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ",a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", np.add(a,b))

Adding 1 to every element: [[11 12]
 [13 14]]

Subtracting 2 from each element: [[-6 -7]
 [-8 -9]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [35]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a,b))
print(a @ b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [6]:
arr1 = np.array([[3,6,7],[2,5,9]])

In [8]:
arr1

array([[3, 6, 7],
       [2, 5, 9]])

In [10]:
print(arr1.min())  # min from whole array

2


In [12]:
print(arr1.min(axis=0))  # axis = 0, means col wise 

[2 5 7]


In [13]:
print(arr1.min(axis=1))  # axis = 1, means row wise 

[3 2]
