In [2]:
import numpy as np

In [3]:
# Reshaping the array 
# 1D array to n dimension array.
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.reshape(1,6))
print(arr.reshape(6,1))
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [4]:
# n dimension to 1D array.
'''
2 methods.
1. ravyel() - onl view
2. flatten() - create copy
'''
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ravel())
print(arr1.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2 = np.arange(2,8).reshape(2,3)

In [7]:
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
# combining 2 arrays

In [9]:
np.hstack((arr1,arr2))   # combine horizontally

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])

In [10]:
np.vstack((arr1,arr2))   # combine vertically

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [18]:
# split the array into equal parts.
np.hsplit(arr2,3)  

[array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([[4],
        [7]])]

In [19]:
np.vsplit(arr2,2)

[array([[2, 3, 4]]), array([[5, 6, 7]])]