### np.sort

In [2]:
# return a sorted array of numpy array type.

import numpy as np
a = np.random.randint(1,100,20)
print(a)

np.sort(a)

[77 47 22 99 96 38 26 91 83 70 39  7  8 75 66 28  6 10 78 85]


array([ 6,  7,  8, 10, 22, 26, 28, 38, 39, 47, 66, 70, 75, 77, 78, 83, 85,
       91, 96, 99], dtype=int32)

In [3]:
# in descending order
np.sort(a)[::-1]

array([99, 96, 91, 85, 83, 78, 77, 75, 70, 66, 47, 39, 38, 28, 26, 22, 10,
        8,  7,  6], dtype=int32)

In [4]:
# for 2d array

b = np.random.randint(1,100,20).reshape(4,5)
print(b)

print(np.sort(b,axis=0))  # col wise sort
print(np.sort(b,axis=1))  # row wise sort

[[76 25 26 46 25]
 [43 72 17 43 71]
 [41 88 56 86 59]
 [99 52 26 80 16]]
[[41 25 17 43 16]
 [43 52 26 46 25]
 [76 72 26 80 59]
 [99 88 56 86 71]]
[[25 25 26 46 76]
 [17 43 43 71 72]
 [41 56 59 86 88]
 [16 26 52 80 99]]


### np.append

In [5]:
# append the value in the mentioned axis at the end

a = np.linspace(1,100,5)
print(a)

np.append(a,200)

[  1.    25.75  50.5   75.25 100.  ]


array([  1.  ,  25.75,  50.5 ,  75.25, 100.  , 200.  ])

In [6]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)  # row wise

array([[76.        , 25.        , 26.        , 46.        , 25.        ,
         0.41741004],
       [43.        , 72.        , 17.        , 43.        , 71.        ,
         0.42709572],
       [41.        , 88.        , 56.        , 86.        , 59.        ,
         0.54369309],
       [99.        , 52.        , 26.        , 80.        , 16.        ,
         0.60271991]])

In [7]:
np.append(b,np.random.random((1,b.shape[1])),axis=0)   # col wise

array([[76.        , 25.        , 26.        , 46.        , 25.        ],
       [43.        , 72.        , 17.        , 43.        , 71.        ],
       [41.        , 88.        , 56.        , 86.        , 59.        ],
       [99.        , 52.        , 26.        , 80.        , 16.        ],
       [ 0.64943381,  0.24067356,  0.62553157,  0.96920099,  0.73658024]])

### np.concatenate

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

In [11]:
# get the unique values from the array

e = np.array([1,2,2,2,4,4,4,1,2,3,3,3,3,6,6,5,5,4])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

In [14]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [15]:
a.shape

(6,)

In [16]:
np.expand_dims(a,axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [17]:
np.expand_dims(a,axis=0).shape

(1, 6)

In [18]:
np.expand_dims(a,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### np.where

In [19]:
a

array([0, 1, 2, 3, 4, 5])

In [21]:
# find all element with value Greater than and equal to 3
np.where(a>=3)

(array([3, 4, 5]),)

In [23]:
# replace all values > 3 with 0
# np.where(condition,if true, if false)
np.where(a>3,0,a)

array([0, 1, 2, 3, 0, 0])

In [25]:
# replace all the even values with 2
np.where(a%2==0,22,a)

array([22,  1, 22,  3, 22,  5])

### np.argmax

In [27]:
# give max value from the array

a
np.argmax(a)

np.int64(5)

In [30]:
b

array([[76, 25, 26, 46, 25],
       [43, 72, 17, 43, 71],
       [41, 88, 56, 86, 59],
       [99, 52, 26, 80, 16]], dtype=int32)

In [29]:
np.argmax(b)  # from the whole array

np.int64(15)

In [32]:
np.argmax(b,axis=0)  # RETURN index , axis=0 (col wise)

array([3, 2, 2, 2, 1])

In [33]:
np.argmax(b,axis=1)  # RETURN index , axis=1 (row wise)

array([0, 1, 1, 0])

### np.argmin

In [34]:
np.argmin(a)

np.int64(0)

In [35]:
np.argmin(b)

np.int64(19)

### np.cumsum

In [37]:
# give the cummitative sum
print(a)
np.cumsum(a)

[0 1 2 3 4 5]


array([ 0,  1,  3,  6, 10, 15])

In [38]:
print(b)
np.cumsum(b)

[[76 25 26 46 25]
 [43 72 17 43 71]
 [41 88 56 86 59]
 [99 52 26 80 16]]


array([  76,  101,  127,  173,  198,  241,  313,  330,  373,  444,  485,
        573,  629,  715,  774,  873,  925,  951, 1031, 1047])

In [39]:
np.cumsum(b,axis=0)

array([[ 76,  25,  26,  46,  25],
       [119,  97,  43,  89,  96],
       [160, 185,  99, 175, 155],
       [259, 237, 125, 255, 171]])

In [40]:
np.cumsum(b,axis=1)

array([[ 76, 101, 127, 173, 198],
       [ 43, 115, 132, 175, 246],
       [ 41, 129, 185, 271, 330],
       [ 99, 151, 177, 257, 273]])

### np.percentile

In [43]:
np.percentile(a,0)  # np.percentile(a,<percentile>)

np.float64(0.0)

In [44]:
np.percentile(a,100)

np.float64(5.0)

In [47]:
print(b)
print(np.percentile(b,0))
print(np.percentile(b,100))
print(np.percentile(b,50))

[[76 25 26 46 25]
 [43 72 17 43 71]
 [41 88 56 86 59]
 [99 52 26 80 16]]
16.0
99.0
49.0


### np.histogram

In [48]:
# this will return histogram values, in the given bins

np.histogram(b,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 4, 0, 4, 3, 0, 3, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [49]:
np.histogram(b,bins=[0,50,100])

(array([10, 10]), array([  0,  50, 100]))

### np.corrcoef

In [50]:
# give the pearson correlation coefficient.

sal = np.array([20000,50000,100000,10000,200000])
exp = np.array([2,4,5,0,7])

np.corrcoef(sal,exp)

array([[1.        , 0.91989281],
       [0.91989281, 1.        ]])

### np.isin

In [54]:
# we can check multiple item that it is in the array or not, (like membership operator)

a = np.random.randint(1,50,20)
b = np.array([2,34,9,14,31,42])

print(a)
print(b)

a[np.isin(a,b)]

[ 2 33  3  1 39 16 36 14 18 26 20 48 26  8 25 25 11 36 16 32]
[ 2 34  9 14 31 42]


array([ 2, 14], dtype=int32)

### np.flip

In [58]:
# it flip the given array , like reverse

print(a)
np.flip(a)

[ 2 33  3  1 39 16 36 14 18 26 20 48 26  8 25 25 11 36 16 32]


array([32, 16, 36, 11, 25, 25,  8, 26, 48, 20, 26, 18, 14, 36, 16, 39,  1,
        3, 33,  2], dtype=int32)

In [70]:
f = np.arange(10,26).reshape(4,4)
print(f)

np.flip(f)  # it will flip , 1st-> left to right , then top to bottom

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


array([[25, 24, 23, 22],
       [21, 20, 19, 18],
       [17, 16, 15, 14],
       [13, 12, 11, 10]])

In [71]:
np.flip(f,axis = 0)

array([[22, 23, 24, 25],
       [18, 19, 20, 21],
       [14, 15, 16, 17],
       [10, 11, 12, 13]])

### np.put

In [81]:
# it replace the value in the given index, multiple at a time.

print(b)

[20 34 90 14 31 24]


In [82]:
np.put(b,[0,2],[100,200])  # np.put(b,[indexs],[values])

In [83]:
print(b)

[100  34 200  14  31  24]


### np.delete

In [90]:
print(e)

np.delete(e,[0,1,17])  # np.delete(e,[indexs])

[1 2 2 2 4 4 4 1 2 3 3 3 3 6 6 5 5 4]


array([2, 2, 4, 4, 4, 1, 2, 3, 3, 3, 3, 6, 6, 5, 5])

### set Functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [92]:
# np.union1d

a = np.array([1,2,3,4,5,6])
b = np.array([3,4,5,6,7,8])

np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.intersect1d(a,b)

array([3, 4, 5, 6])

In [95]:
np.setdiff1d(a,b)  # setdiff(a,b) -> in a but not in b

array([1, 2])

In [96]:
np.setdiff1d(b,a)

array([7, 8])

In [97]:
np.setxor1d(a,b)  # return (a union b) - (a intersect b)

array([1, 2, 7, 8])

In [106]:
a[np.in1d(b,4)]

C:\Users\hdewa\AppData\Local\Temp\ipykernel_14876\3452238120.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a[np.in1d(b,4)]


array([2])

### np.clip

In [114]:
# trim the values which are exceeding the limits and replace with the max and min limits

x = np.random.randint(1,100,10)
print(x)



[54 45 52 11 36 70 58  9 76 96]


In [115]:
np.clip(x,min = 25,max= 75)

array([54, 45, 52, 25, 36, 70, 58, 25, 75, 75], dtype=int32)